import { Project } from '@/types/projects';

export const projects: Project[] = [
  {
    image: '/loopit.png',
    title: 'LOOPIT',
    description: 'IT 수리 및 중고판매 플랫폼 서비스',
    tags: [
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Swiper',
      'TanStack Query',
      'Zustand',
      'React Hook Form',
      'Zod',
      'React Router 7',
      'WebSocket(STOMP)',
      'Vite',
      'Yarn',
      'Storybook',
      'Vitest',
      'Cypress',
      'GitHub Action',
      'Vercel',
    ],
    links: {
      demo: 'https://www.loopit.kro.kr/',
      github: 'https://github.com/Leets-Official/LOOPIT-FE',
    },
    teamSize: '8명',
    period: '2025.12 - 2026.02',
    contributionRate: '50%',
    detailedDescription:
      '중고 물품의 구매·판매부터 수리점 찾기, 실시간 채팅까지 원스톱으로 제공하는 종합 중고거래 플랫폼',
    features: [
      'LOOPIT은 중고 스마트 기기에 새로운 쓸모를 찾아줍니다.',

      '실시간 채팅으로 판매자와 직접 소통하고,', 

      'AI 챗봇이 거래를 도와주며, 기기에 문제가 생기면 수리 서비스까지 연결됩니다',
    ],
    contributions: [
      'FE 3명의 파트 리더로서 아키텍처 선정, 코드 컨벤션, PR 리뷰 기준을 정의하고 일관된 개발 환경 구축',
      '페이지 간 컴포넌트·로직 중복을 방지하기 위해 FSD 아키텍처를 도입하고, 14개 커스텀 Hook과 6개 유틸을 shared 레이어로 표준화해 재사용 기반 마련',
      'Tailwind CSS 4 + CSS 변수 기반 디자인 토큰 체계를 설계하고, 28개 공통 UI 컴포넌트를 구축 및 Storybook 21개 스토리로 문서화해 FE 간 구현 편차 제거',
      'React Router 7 SSR + React Compiler 적용으로 Lighthouse 성능 94점·SEO 100점·FCP 2.1초 달성',
      'SSR 환경에서 Zustand persist Hydration mismatch 원인을 분석하고, _hasHydrated 패턴을 도입해 해결',
      'STOMP 기반 실시간 채팅에서 네트워크 불안정 시 연결 끊김 문제를 자동 재연결·heartbeat로 해결',
      '수동 검증 비용을 줄이기 위해 8개 GitHub Actions 워크플로우를 구축하고, Vitest 유닛 29개 + Cypress E2E로 리팩터링 시 회귀 방지',
    ],
    reflections: [
      'React Router 7 layout API로 라우팅 구조를 한눈에 관리하며 확장·유지보수가 쉬워짐을 체감했습니다',
      'FSD를 적용해 레이어 의존성을 명확히 하자 충돌이 줄고 병렬 작업이 자연스러워졌습니다.',
      '디자인 토큰을 구축하며 색상 변경이 전 서비스에 일관되게 반영되는 경험으로 시스템 설계의 가치를 배웠습니다.',
      '25+ 컴포넌트를 Storybook으로 문서화하며 문서가 협업 속도를 좌우한다는 점을 확인했습니다.',
      'Cypress E2E 테스트로 리팩토링·기능 추가에 자신감을 주는 안전장치의 의미를 경험했습니다.',
    ],
  },
  {
    image: '/dtalks.png',
    title: 'DTalks',
    description: 'RAG 기반 AI Chatbot을 활용한 사내문서 관리 시스템',
    tags: [
      'React',
      'React Router',
      'TypeScript',
      'Styled-Components',
      'Recharts',
      'ApexCharts',
      'TanStack Query',
      'Zustand',
      'React Hook Form',
      'Yup',
      'Vite',
      'KakaoCloud',
    ],
    links: {
      demo: 'https://youtu.be/FJiiPrAlXc8',
      github: 'https://github.com/DTaIks',
    },
    teamSize: '10명',
    period: '2025.07 - 2025.08',
    contributionRate: '60%',
    detailedDescription:
      '사내 문서를 쉽고 효율적으로 활용할 수 있도록 돕는 RAG 기반 챗봇 및 데이터 관리 시스템',
    features: [
      'Auth: 이메일 기반 회원가입 및 로그인 기능',
      'AI Chatbot (RAG 기반)',
      '└ 다중 계층 필터링을 활용한 가드레일 기능',
      '└ 프롬프트 기반 주제별 질의응답 기능',
      '└ 사용자 피드백 기반 실시간 응답 품질 개선 기능',
      '└ FAQ / 용어사전 / 정책 문서 등 사내 자료를 활용한 RAG 응답 기능',
      '└ 다국어 지원 및 스몰톡 기능',
      '└ 문맥 유지 / 응답 캐싱 기능',
      'Admin Page',
      '└ 프롬프트 템플릿별 사용 통계 시각화',
      '└ 사용자 검색 및 권한 관리 기능',
      '└ 카테고리별 사내 문서 관리 (용어사전, 정책, 보고서 양식 등)',
      '└ 문서별 버전 관리 및 히스토리 조회',
      '└ 버전 간 수정사항 비교 기능',
      '└ 부서별 미디어 파일(문서, 이미지, 음성) 업로드 및 관리',
      '└ FAQ 카테고리 및 문서 등록/편집/삭제 기능',
    ],
    contributions: [
      'FE 파트 리더로서 GitHub Flow 기반 브랜치 전략, 코드 리뷰 프로세스, ESLint/Prettier 규칙을 정의해 FE 2명의 협업 기준 수립',
      '인증 여부에 따라 레이아웃이 달라지는 구조를 React Router v6 Outlet 패턴으로 분리하고, 반복되는 UI를 공통 컴포넌트(Design System)로 추출',
      '페이지 전환마다 동일 API가 반복 호출되는 문제를 React Query 캐싱 전략으로 해결, 중복 호출 80% 감소 및 로딩 2~3초 → 1.5초 개선',
      'Zustand 스토어를 도메인별로 분리·모듈화해 FE 간 상태 충돌을 제거하고 독립적 개발이 가능하도록 구조화',
      '검색 입력마다 발생하던 API 호출을 디바운스로 최적화, 불필요한 호출 약 70% 감소',
      '문서 버전 관리 및 변경 시 실시간 UI 피드백을 구현해 운영자가 문서 상태를 즉시 확인 가능하도록 개선',
      'ApexCharts·ReCharts로 대시보드/통계 시각화를 구현해 비개발 직군도 운영 지표를 직관적으로 파악 가능',
      '권한 부족·에러·로딩 등 예외 시나리오별 표준 UI를 정의해 사용자 경험 일관성 확보',
      'Kakao Cloud Object Storage + CDN으로 정적 배포 파이프라인 및 CI/CD 자동화 구축',
    ],
    reflections: [
      '화면이 아닌 업무 흐름 단위로 설계해야 직관적인 UX가 나온다는 걸 배웠습니다.',
      '서버/클라이언트 상태를 명확히 분리할수록 구조가 단순해지고 확장성이 높아짐을 깨달았습니다.',
      '폼 검증은 실수를 막는 게 아니라 흐름을 안내하는 UX가 되어야 한다는 걸 체감했습니다.',
      '비정상 흐름에서도 끊기지 않는 경험이 서비스 완성도를 결정한다는 점을 알게 됐습니다.',
      '협업 생산성은 속도가 아닌 누구나 참여 가능한 구조에서 나온다는 걸 느꼈습니다.',
    ],
  },
  {
    image: '/alog.jpg',
    title: 'Alog',
    description: 'AI를 이용한 개발자 친화적 블로그 서비스 Alog',
    tags: [
      'React',
      'React Router',
      'JavaScript',
      'Framer Motion',
      'React Quill',
      'Mantine',
      'Zustand',
      'WebSocket',
      'SSE',
      'Vite',
      'Three.js',
      'Figma',
    ],
    links: {
      demo: 'https://youtu.be/ZYel_wNa28c?si=P61EYzMuTr9aQ7Aq',
      github: 'https://github.com/Gachon-Univ-Creative-Code-Innovation',
    },
    teamSize: '8명',
    period: '2025.03 - 2025.06',
    contributionRate: '50%',
    detailedDescription:
      'Alog는 개발자들이 자신의 역량을 효과적으로 표현하고, 협업과 커뮤니티 활동을 통해 함께 성장할 수 있도록 지원하는 MSA 와 AI 기반 커리어 매칭 플랫폼',
    features: [
      '회원가입 / 로그인: 일반 가입 및 카카오, 구글 기반 소셜 로그인 기능 제공',
      '블로그 글쓰기 / AI 요약: 사용자가 작성한 글을 기반으로 AI가 자동 요약 및 태그 추출',
      'README 자동 생성: 깃허브 정보와 기술 태그를 활용해 README 초안을 자동 구성',
      '개발자 매칭 기능: 기술 태그 유사도 기반으로 유저 매칭 및 프로필 열람 기능 지원',
      '포트폴리오 자동 완성: 글/태그/깃허브 기반으로 포트폴리오 초안 자동 생성 기능 제공',
      '채팅: 실시간 WebSocket 기반의 쪽지/채팅 기능 지원',
      '알림: 댓글/팔로우/쪽지 등 실시간 알림 실시간 수신 가능',
      '로드맵 추천: 유저의 기술 태그와 관심사 기반으로 커리어 로드맵 추천 기능 제공',
    ],
    contributions: [
      '사용자 행동 흐름 분석을 기반으로 화면별 피드백 시나리오를 기획하고, 기획→구현까지 직접 담당',
      '에디터에서 사용자 입력 HTML을 그대로 렌더링하던 XSS 취약점을 발견하고, DOMPurify를 도입해 보안 리스크 제거',
      '이미지 업로드 시 서버 부하를 줄이기 위해 S3 Presigned URL 방식을 도입하고, ReactQuill에 드래그앤드롭·진행률 UI를 추가해 작성 경험 개선',
      'WebSocket/SSE 기반 실시간 메시지·알림을 구현하고, 연결 끊김 시 자동 재연결 로직으로 안정성 확보',
      'Axios 인터셉터로 토큰 갱신·만료 처리와 공통 에러 핸들링을 표준화해 인증 관련 반복 코드 제거',
      '서버 상태와 클라이언트 UI 상태를 Context API/Zustand로 목적별 분리해 데이터 흐름 단순화',
      '페이지 전환 시 콘텐츠가 즉시 교체되어 어색한 문제를 CSS Transition·Framer Motion으로 자연스러운 전환 애니메이션을 적용해 개선',
    ],
    reflections: [
      '사용자 여정 단위로 사고하며 화면이 아닌 흐름 전체를 설계하는 습관을 갖게 됐습니다.',
      'MSA 환경에서 서비스 간 데이터 흐름 설계가 프론트엔드의 중요한 역할임을 깨달았습니다.',
      '지연/비정상 응답 상황에서도 UI 흐름이 끊기지 않도록 설계하는 것이 진짜 UX임을 알게 됐습니다.',
      'Zustand 기반 전역 상태 관리로 페이지 전환 후에도 데이터 맥락을 유지하는 구조의 가치를 배웠습니다.',
      '짧은 일정에서도 우선순위 판단과 집중을 통해 제한된 리소스 내에서 완성도를 높이는 역량을 키웠습니다.',
    ],
  },
  {
    image: '/portfolio.png',
    title: 'Portfolio Website',
    description:
      '클린 아키텍처와 디자인 시스템 기반의 확장 가능한 포트폴리오 웹사이트입니다. Panda CSS의 제로 런타임 CSS-in-JS와 체계적인 컴포넌트 구조로 성능과 유지보수성을 극대화했습니다.',
    tags: [
      'React',
      'Next.js',
      'TypeScript',
      'Panda CSS',
      'Framer Motion',
      'Iconify React',
      'Pnpm',
      'Vercel',
    ],
    links: {
      demo: '/',
      github: 'https://github.com/KyeongJooni/Portfolio',
    },
    teamSize: '1명',
    period: '2025.09 - 진행중',
    contributionRate: '100% (Solo)',
    detailedDescription:
      '성능과 확장성을 모두 고려한 현대적인 포트폴리오 웹사이트입니다. Panda CSS의 제로 런타임 특성으로 CSS-in-JS의 성능 문제를 해결하고, Recipe 시스템으로 컴포넌트 변형을 타입 안전하게 관리합니다. 스타일과 로직의 완전한 분리, 토큰 기반 디자인 시스템으로 일관성 있는 UI를 구축했습니다.',
    features: [
      'Panda CSS 제로 런타임 & Recipe 시스템으로 성능과 타입 안전성 확보',
      '토큰 기반 디자인 시스템(colors, spacing, typography)으로 일관된 UI 구현',
      '스타일/로직 완전 분리 아키텍처로 유지보수성 극대화',
      'Framer Motion 스크롤 애니메이션과 인터랙션 최적화',
      '반응형 디자인 & 다크/라이트 모드 완벽 지원',
      'Next.js App Router, Dynamic Import로 코드 스플리팅 및 초기 로딩 최적화',
    ],
    contributions: [
      'Lighthouse 성능 최적화: Performance 91 / Accessibility 98 / Best Practices 100 / SEO 100 달성',
      '전역 styles/ 폴더 구조로 Recipe와 정적 스타일 체계화, 재사용성과 확장성 확보',
      'Navigation, Skills Tab 등 반복 패턴을 Recipe로 추상화하여 변형 관리 간소화',
      'CSS 변수 활용으로 동적 스타일(레벨바 width 등) 성능 최적화',
      '인라인 스타일 제거 및 스타일 파일 분리로 관심사 분리',
      'Panda CSS staticCss 설정으로 동적 variant CSS 사전 생성, 런타임 오버헤드 제거',
      'Iconify React로 아이콘 시스템 통합, 일관된 비주얼 언어 구축',
      'constants/ 폴더로 데이터 중앙화, 컴포넌트와 데이터 의존성 최소화',
    ],
    reflections: [
      '디자인 시스템을 직접 설계하면서 일관성 있는 UI가 개발 속도와 유지보수성에 미치는 영향을 체감했습니다.',
      'Panda CSS의 제로 런타임 특성을 활용하면서 CSS-in-JS의 DX와 성능 사이의 균형을 이해하게 되었습니다.',
      '애니메이션 설계 과정에서 과하지 않으면서도 사용자 경험을 향상시키는 모션의 중요성을 배웠습니다.',
      '혼자 진행한 프로젝트였지만, 협업을 고려한 구조와 문서화가 미래의 확장성을 결정한다는 것을 느꼈습니다.',
    ],
  },
];
