export type SkillIconEntry = {
  icon: string; // iconify icon name
  color?: string;
};

export const skillIconMap: Record<string, SkillIconEntry> = {
  React: { icon: 'simple-icons:react', color: '#61DAFB' },
  Flutter: { icon: 'simple-icons:flutter', color: '#02569B' },
  'Next.js': { icon: 'simple-icons:nextdotjs', color: '#000000' },
  TypeScript: { icon: 'simple-icons:typescript', color: '#3178C6' },
  JavaScript: { icon: 'simple-icons:javascript', color: '#F7DF1E' },
  CSS3: { icon: 'simple-icons:css3', color: '#1572B6' },
  Tailwind: { icon: 'simple-icons:tailwindcss', color: '#38BDF8' },
  'Styled Components': { icon: 'simple-icons:styledcomponents', color: '#DB7093' },
  'Panda CSS': { icon: 'emojione:panda-face' },
  'Node.js': { icon: 'simple-icons:nodedotjs', color: '#339933' },
  Express: { icon: 'simple-icons:express', color: '#000000' },
  MongoDB: { icon: 'simple-icons:mongodb', color: '#47A248' },
  Docker: { icon: 'simple-icons:docker', color: '#2496ED' },
  'CI/CD': { icon: 'simple-icons:githubactions', color: '#2088FF' },
  Git: { icon: 'simple-icons:git', color: '#F05032' },
  Figma: { icon: 'simple-icons:figma', color: '#F24E1E' },
  Framer: { icon: 'simple-icons:framer', color: '#0055FF' },
  Vercel: { icon: 'simple-icons:vercel', color: '#000000' },
  Zustand: { icon: 'emojione-v1:bear-face' },
  Zod: { icon: 'simple-icons:zod' },
  'Three.js': { icon: 'simple-icons:threedotjs', color: '#000000' },
  'Framer Motion': { icon: 'simple-icons:framer', color: '#0055FF' },
  'React Query': { icon: 'simple-icons:reactquery', color: '#FF4154' },
  'React Hook Form': { icon: 'simple-icons:reacthookform', color: '#EC5990' },
  'React Router': { icon: 'simple-icons:reactrouter', color: '#CA4245' },
  Vite: { icon: 'simple-icons:vite', color: '#646CFF' },
  WebSocket: { icon: 'mdi:lan-connect', color: '#0ea5e9' },
  SSE: { icon: 'mdi:radio-tower', color: '#0ea5e9' },
  Yarn: { icon: 'simple-icons:yarn', color: '#2C8EBB' },
  Pnpm: { icon: 'simple-icons:pnpm', color: '#F69220' },
  'Chart.js': { icon: 'simple-icons:chartdotjs', color: '#FF6384' },
  MySQL: { icon: 'simple-icons:mysql', color: '#4479A1' },
  'Ant Design': { icon: 'simple-icons:antdesign', color: '#0170FE' },
  'React-Bootstrap': { icon: 'simple-icons:bootstrap', color: '#7952B3' },
  Jest: { icon: 'simple-icons:jest', color: '#C21325' },
  Vitest: { icon: 'simple-icons:vitest', color: '#6E9F18' },
  Cypress: { icon: 'simple-icons:cypress', color: '#00BFA5' },
  'Testing Library': { icon: 'simple-icons:testinglibrary', color: '#E34F26' },
  MSW: { icon: 'mdi:api', color: '#ff9800' },
  HTML: { icon: 'simple-icons:html5', color: '#E34F26' },
  Netlify: { icon: 'simple-icons:netlify', color: '#00C7B7' },
  Amplify: { icon: 'simple-icons:awsamplify', color: '#FF9900' },
  Nginx: { icon: 'simple-icons:nginx', color: '#009639' },
  EC2: { icon: 'simple-icons:amazonec2', color: '#FF9900' },
  AWS: { icon: 'simple-icons:amazonaws', color: '#FF9900' },
  CloudFront: { icon: 'mdi:cloud-outline', color: '#FF9900' },
  S3: { icon: 'simple-icons:amazons3', color: '#569A31' },
  KakaoCloud: { icon: 'simple-icons:kakaotalk', color: '#FFCD00' },
  'GitHub Actions': { icon: 'simple-icons:githubactions', color: '#2088FF' },
  GitHub: { icon: 'simple-icons:github', color: '#181717' },
  Slack: { icon: 'simple-icons:slack', color: '#4A154B' },
  Jira: { icon: 'simple-icons:jira', color: '#2684FF' },
  Notion: { icon: 'simple-icons:notion', color: '#000000' },
};

