import {
  SiCypress,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGithubactions,
  SiJavascript,
  SiMantine,
  SiNextdotjs,
  SiPnpm,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiStorybook,
  SiStyledcomponents,
  SiSwiper,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiYarn,
  SiZod,
  type IconType,
} from '@icons-pack/react-simple-icons';
import ZustandTagIcon from '@/components/ui/icons/ZustandTagIcon';

export type TagIconEntry = {
  Icon: IconType;
  color: string;
};

export const tagIconMap: Record<string, TagIconEntry> = {
  React: { Icon: SiReact, color: '#61DAFB' },
  'React 19': { Icon: SiReact, color: '#61DAFB' },
  TypeScript: { Icon: SiTypescript, color: '#3178C6' },
  'Tailwind CSS': { Icon: SiTailwindcss, color: '#06B6D4' },
  'Styled-Components': { Icon: SiStyledcomponents, color: '#DB7093' },
  'React Query': { Icon: SiReactquery, color: '#FF4154' },
  'TanStack Query': { Icon: SiReactquery, color: '#FF4154' },
  'React Hook Form': { Icon: SiReacthookform, color: '#EC5990' },
  Zod: { Icon: SiZod, color: '#3E67B1' },
  Zustand: { Icon: ZustandTagIcon, color: '#7A5030' },
  Vite: { Icon: SiVite, color: '#646CFF' },
  Yarn: { Icon: SiYarn, color: '#2C8EBB' },
  Storybook: { Icon: SiStorybook, color: '#FF4785' },
  Swiper: { Icon: SiSwiper, color: '#6332F6' },
  Vitest: { Icon: SiVitest, color: '#6E9F18' },
  Cypress: { Icon: SiCypress, color: '#69D3A7' },
  'GitHub Action': { Icon: SiGithubactions, color: '#2088FF' },
  'GitHub Actions': { Icon: SiGithubactions, color: '#2088FF' },
  JavaScript: { Icon: SiJavascript, color: '#F7DF1E' },
  Firebase: { Icon: SiFirebase, color: '#FFCA28' },
  'Framer Motion': { Icon: SiFramer, color: '#0055FF' },
  'Next.js': { Icon: SiNextdotjs, color: '#000000' },
  Figma: { Icon: SiFigma, color: '#F24E1E' },
  'Three.js': { Icon: SiThreedotjs, color: '#000000' },
  Vercel: { Icon: SiVercel, color: '#000000' },
  Pnpm: { Icon: SiPnpm, color: '#F69220' },
  'React Router': { Icon: SiReactrouter, color: '#CA4245' },
  'React Router 7': { Icon: SiReactrouter, color: '#CA4245' },
  Mantine: { Icon: SiMantine, color: '#339AF0' },
};

